# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0016_eventdesign_html'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO '
            'banner_eventdesign("name","created","changed","user_id","html") '
            'VALUES (\'default\',\'2018-04-04 11:57:38'
            '.344572-03\',\'2018-04-04 11:57:38.344603-03\','
            '1,\''
            '<div style="width:100vw; height: 100vh;">'
            '<div class="banner">'
            '<div class="top-row" style="font: 65px sans-serif; '
            'text-align: center;">{title}</div>'
            '<div id="firstDivision" class="left-top-corner-division">'
            '<img style="border-radius: 15px;" '
            'src="{logo}" height="100%" width="100%"></div>'
            '<div id="fourthDivision" class="right-top-corner-division">'
            '<div class="event-qr" id="qrcode-{id}"></div>'
            '</div><div id="thirdDivision" '
            'class="left-bottom-corner-division">'
            '<div style="margin-top: 2%; margin-bottom: 2%; margin-left: 2%; '
            'font: 20px sans-serif; text-align: center">{description}</div>'
            '</div><div id="secondDivision" '
            'class="right-bottom-corner-division">'
            '<div style="margin: 10%; text-align: center;"><div>'
            '<span style="font: 40px arial, sans-serif;">'
            '{startdate_month} {startdate_day}</span></div>'
            '<div style="margin-top: 20%;"><span style="font: 50px arial, '
            'sans-serif; background: orange; '
            'border-radius: 10px; padding: 4%;">'
            '{tinyurl}</span></div></div></div></div></div>'
            '\');'
        )
    ]
