# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0021_auto_20180503_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banner.Banner'),
        ),
    ]
