# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0022_auto_20180507_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='event_design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banner.EventDesign'),
            preserve_default=False,
        ),
    ]
