# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0022_auto_20180507_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='custom_cover',
            field=models.FileField(max_length=500, null=True, upload_to=b'custom_cover/'),
        ),
    ]
